production:
  adapter: postgresql
  encoding: UTF8
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  database: bantimwe_db
  username: bantimwe_admin
  password: b4ntimwe_4dmin
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000